/*
Copyright 2025 The llm-d-inference-sim Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package simulator

import (
	"math"
	"sort"
	"sync"
	"time"

	"github.com/llm-d/llm-d-inference-sim/pkg/common"
)

// These values intentionally match vLLM 0.27.1 EPLB defaults. vLLM records
// expert load only near a rearrangement, using a 1000-step sliding window, and
// attempts an expert rearrangement every 3000 forward steps.
const (
	vllmEPLBWindowSize   = 1000
	vllmEPLBStepInterval = 3000
)

type moeLatencyCacheKey struct {
	generation uint64
	tokens     int
}

type moeSimulator struct {
	numGPUs             int
	numExperts          int
	physicalSlots       int
	topK                int
	numLayers           int
	router              string
	gpuFlops            float64
	gpuBandwidth        float64
	interconnectBW      float64
	interconnectLatency time.Duration
	expertWeightBytes   float64
	flopsPerAssignment  float64
	activationBytes     float64
	networkBytes        float64
	probabilities       []float64

	// placements[layer][logicalExpert] is the set of EP ranks that currently
	// hold a physical copy of that logical expert.
	placements [][][]int

	// EPLB state mirrors the timing and load-window semantics in vLLM. The
	// simulator records the logical load generated by each simulated forward;
	// this is equivalent to vLLM summing the physical-replica counters back to
	// logical experts before invoking the configured EPLB policy.
	eplbLoadWindow          []float64
	eplbLoadWindowStep      int
	expertRearrangementStep int
	placementGeneration     uint64
	lastReplacementMoves    int

	stateMu      sync.Mutex
	latencyCache map[moeLatencyCacheKey]time.Duration
}

type moeRoutingState struct {
	active []map[int]struct{}
	loads  []float64
}

func newMoESimulator(config *common.Configuration) *moeSimulator {
	m := &moeSimulator{
		numGPUs:             config.MoEExpertParallelSize,
		numExperts:          config.MoENumExperts,
		physicalSlots:       config.MoEPhysicalExpertSlots,
		topK:                config.MoETopK,
		numLayers:           config.MoENumLayers,
		router:              config.MoERouter,
		gpuFlops:            config.MoEGPUFlops,
		gpuBandwidth:        config.MoEGPUMemoryBandwidth,
		interconnectBW:      config.MoEInterconnectBandwidth,
		interconnectLatency: config.MoEInterconnectLatency,
		latencyCache:        make(map[moeLatencyCacheKey]time.Duration),
	}

	d := float64(config.MoEHiddenSize)
	dff := float64(config.MoEIntermediateSize)
	bytesPerElement := float64(config.MoEBytesPerElement)
	m.expertWeightBytes = 3 * d * dff * bytesPerElement
	m.flopsPerAssignment = 2 * 3 * d * dff
	m.activationBytes = (2*d + dff) * bytesPerElement
	m.networkBytes = d * bytesPerElement
	m.probabilities = powerLawProbabilities(m.numExperts, config.MoEExpertPopularityAlpha)

	// Match vLLM's initial EPLB state exactly: physical_to_logical starts as
	// [0..numExperts-1, 0, 1, ...] and physical slots are contiguous by EP
	// rank. The same initial map is duplicated across all MoE layers. D'Hondt
	// is not used until the first EPLB rearrangement.
	initial := vllmInitialPlacementOneLayer(m.numExperts, m.physicalSlots, m.numGPUs)
	m.placements = make([][][]int, m.numLayers)
	for layer := range m.numLayers {
		m.placements[layer] = clonePlacement(initial)
	}

	m.eplbLoadWindow = make([]float64, vllmEPLBWindowSize*m.numLayers*m.numExperts)
	// vLLM starts the rearrangement counter at 3/4 of the configured interval,
	// so the first online rebalance happens after one quarter of the interval.
	m.expertRearrangementStep = vllmEPLBStepInterval - vllmEPLBStepInterval/4
	return m
}

func powerLawProbabilities(numExperts int, alpha float64) []float64 {
	probabilities := make([]float64, numExperts)
	total := 0.0
	for expert := range numExperts {
		weight := math.Pow(float64(expert+1), -alpha)
		probabilities[expert] = weight
		total += weight
	}
	for expert := range probabilities {
		probabilities[expert] /= total
	}
	return probabilities
}

// vllmInitialPlacementOneLayer reproduces
// EplbState.build_initial_global_physical_to_logical_map() followed by vLLM's
// contiguous physical-slot ownership by EP rank. No load trace participates in
// initial placement.
func vllmInitialPlacementOneLayer(numExperts, physicalSlots, numGPUs int) [][]int {
	if numExperts < 1 || physicalSlots < numExperts || numGPUs < 1 {
		panic("invalid MoE expert placement dimensions")
	}
	if physicalSlots%numGPUs != 0 {
		panic("physical expert slots must be divisible by expert parallel size")
	}
	if physicalSlots > numExperts*numGPUs {
		panic("physical expert slots exceed one replica per expert per GPU")
	}

	slotsPerRank := physicalSlots / numGPUs
	physicalToLogical := make([]int, physicalSlots)
	for expert := range numExperts {
		physicalToLogical[expert] = expert
	}
	for slot := numExperts; slot < physicalSlots; slot++ {
		physicalToLogical[slot] = (slot - numExperts) % numExperts
	}

	placement := make([][]int, numExperts)
	for slot, expert := range physicalToLogical {
		rank := slot / slotsPerRank
		placement[expert] = append(placement[expert], rank)
	}
	return placement
}

func clonePlacement(placement [][]int) [][]int {
	clone := make([][]int, len(placement))
	for expert := range placement {
		clone[expert] = append([]int(nil), placement[expert]...)
	}
	return clone
}

// dhondtPlaceOneLayer is a direct Go port of
// MoE-Token-Router-Project/moe_all_files/dhondt/dhondt_core.py. It preserves
// the reference algorithm's tie-breaking, replica cap, and equal number of
// physical expert slots per EP rank.
func dhondtPlaceOneLayer(load []float64, physicalSlots, numGPUs int) ([][]int, []int) {
	numExperts := len(load)
	if physicalSlots < numExperts {
		panic("physical expert slots must be at least the logical expert count")
	}
	if physicalSlots%numGPUs != 0 {
		panic("physical expert slots must be divisible by expert parallel size")
	}
	if physicalSlots > numExperts*numGPUs {
		panic("physical expert slots exceed one replica per expert per GPU")
	}

	replicaCount := make([]int, numExperts)
	for expert := range replicaCount {
		replicaCount[expert] = 1
	}

	remaining := physicalSlots - numExperts
	for remaining > 0 {
		bestExpert := -1
		bestScore := math.Inf(-1)
		for expert, expertLoad := range load {
			if replicaCount[expert] >= numGPUs {
				continue
			}
			score := expertLoad / float64(replicaCount[expert]+1)
			// Experts are visited in ascending ID order. Not replacing on an
			// equal score matches Python heap tuple tie-breaking by expert ID.
			if bestExpert < 0 || score > bestScore {
				bestExpert = expert
				bestScore = score
			}
		}
		if bestExpert < 0 {
			panic("unable to allocate all physical expert slots")
		}
		replicaCount[bestExpert]++
		remaining--
	}

	placement := make([][]int, numExperts)
	rankSlots := make([]int, numGPUs)
	experts := make([]int, numExperts)
	for expert := range experts {
		experts[expert] = expert
	}
	// Python sorted() is stable. Equal replica counts therefore retain
	// ascending expert ID order.
	sort.SliceStable(experts, func(i, j int) bool {
		return replicaCount[experts[i]] > replicaCount[experts[j]]
	})

	for _, expert := range experts {
		ranks := make([]int, numGPUs)
		for rank := range ranks {
			ranks[rank] = rank
		}
		// Equal rank occupancy retains ascending rank order, matching the
		// reference sorted(range(num_ranks), key=rank_slots[rank]).
		sort.SliceStable(ranks, func(i, j int) bool {
			return rankSlots[ranks[i]] < rankSlots[ranks[j]]
		})
		for _, rank := range ranks[:replicaCount[expert]] {
			placement[expert] = append(placement[expert], rank)
			rankSlots[rank]++
		}
	}

	expectedSlotsPerRank := physicalSlots / numGPUs
	for _, slots := range rankSlots {
		if slots != expectedSlotsPerRank {
			panic("D'Hondt placement did not fill EP ranks equally")
		}
	}
	return placement, replicaCount
}

func containsGPU(gpus []int, target int) bool {
	for _, gpu := range gpus {
		if gpu == target {
			return true
		}
	}
	return false
}

func expertOrder(values []float64) []int {
	order := make([]int, len(values))
	for index := range order {
		order[index] = index
	}
	sort.SliceStable(order, func(i, j int) bool {
		if values[order[i]] == values[order[j]] {
			return order[i] < order[j]
		}
		return values[order[i]] > values[order[j]]
	})
	return order
}

func newMoERoutingState(numGPUs int) *moeRoutingState {
	state := &moeRoutingState{
		active: make([]map[int]struct{}, numGPUs),
		loads:  make([]float64, numGPUs),
	}
	for gpu := range numGPUs {
		state.active[gpu] = make(map[int]struct{})
	}
	return state
}

func (s *moeRoutingState) clone() *moeRoutingState {
	clone := newMoERoutingState(len(s.loads))
	copy(clone.loads, s.loads)
	for gpu := range s.active {
		for expert := range s.active[gpu] {
			clone.active[gpu][expert] = struct{}{}
		}
	}
	return clone
}

func (m *moeSimulator) gpuCost(activeExperts int, assignments float64) float64 {
	memorySeconds := (float64(activeExperts)*m.expertWeightBytes + assignments*m.activationBytes) / m.gpuBandwidth
	computeSeconds := assignments * m.flopsPerAssignment / m.gpuFlops
	return math.Max(memorySeconds, computeSeconds)
}

func (m *moeSimulator) maxGPUCost(state *moeRoutingState) float64 {
	maxCost := 0.0
	for gpu := range m.numGPUs {
		cost := m.gpuCost(len(state.active[gpu]), state.loads[gpu])
		if cost > maxCost {
			maxCost = cost
		}
	}
	return maxCost
}

func (m *moeSimulator) routeSplit(counts []float64, placement [][]int) *moeRoutingState {
	state := newMoERoutingState(m.numGPUs)
	for expert, count := range counts {
		if count <= 0 {
			continue
		}
		share := count / float64(len(placement[expert]))
		for _, gpu := range placement[expert] {
			state.active[gpu][expert] = struct{}{}
			state.loads[gpu] += share
		}
	}
	return state
}

func (m *moeSimulator) routeConcentrate(counts []float64, placement [][]int) *moeRoutingState {
	state := newMoERoutingState(m.numGPUs)
	for _, expert := range expertOrder(counts) {
		count := counts[expert]
		if count <= 0 {
			continue
		}
		bestGPU := -1
		bestCost := math.Inf(1)
		for _, gpu := range placement[expert] {
			candidate := state.clone()
			candidate.active[gpu][expert] = struct{}{}
			candidate.loads[gpu] += count
			cost := m.maxGPUCost(candidate)
			if cost < bestCost || (cost == bestCost && (bestGPU < 0 || gpu < bestGPU)) {
				bestGPU = gpu
				bestCost = cost
			}
		}
		state.active[bestGPU][expert] = struct{}{}
		state.loads[bestGPU] += count
	}
	return state
}

func (m *moeSimulator) routeHeuristic(counts []float64, placement [][]int) *moeRoutingState {
	state := newMoERoutingState(m.numGPUs)
	chosen := make(map[int][]int)
	weightSeconds := m.expertWeightBytes / m.gpuBandwidth
	computeSeconds := m.flopsPerAssignment / m.gpuFlops

	for _, expert := range expertOrder(counts) {
		count := counts[expert]
		if count <= 0 {
			continue
		}
		replicaCount := int(math.Ceil(count * computeSeconds / weightSeconds))
		if replicaCount < 1 {
			replicaCount = 1
		}
		if replicaCount > len(placement[expert]) {
			replicaCount = len(placement[expert])
		}
		share := count / float64(replicaCount)
		selected := make([]int, 0, replicaCount)
		for range replicaCount {
			bestGPU := -1
			bestCost := math.Inf(1)
			for _, gpu := range placement[expert] {
				if containsGPU(selected, gpu) {
					continue
				}
				candidate := state.clone()
				candidate.active[gpu][expert] = struct{}{}
				candidate.loads[gpu] += share
				cost := m.maxGPUCost(candidate)
				if cost < bestCost || (cost == bestCost && (bestGPU < 0 || gpu < bestGPU)) {
					bestGPU = gpu
					bestCost = cost
				}
			}
			selected = append(selected, bestGPU)
			state.active[bestGPU][expert] = struct{}{}
			state.loads[bestGPU] += share
		}
		chosen[expert] = selected
	}

	for range 20 {
		before := m.maxGPUCost(state)
		slowGPU := 0
		slowCost := -1.0
		for gpu := range m.numGPUs {
			cost := m.gpuCost(len(state.active[gpu]), state.loads[gpu])
			if cost > slowCost {
				slowGPU = gpu
				slowCost = cost
			}
		}
		improved := false
		activeExperts := make([]int, 0, len(state.active[slowGPU]))
		for expert := range state.active[slowGPU] {
			activeExperts = append(activeExperts, expert)
		}
		sort.Ints(activeExperts)
		for _, expert := range activeExperts {
			selected := chosen[expert]
			if len(selected) != 1 || selected[0] != slowGPU {
				continue
			}
			for _, destination := range placement[expert] {
				if destination == slowGPU {
					continue
				}
				candidate := state.clone()
				delete(candidate.active[slowGPU], expert)
				candidate.loads[slowGPU] -= counts[expert]
				candidate.active[destination][expert] = struct{}{}
				candidate.loads[destination] += counts[expert]
				if m.maxGPUCost(candidate)+1e-15 < before {
					state = candidate
					chosen[expert] = []int{destination}
					improved = true
					break
				}
			}
			if improved {
				break
			}
		}
		if !improved {
			break
		}
	}
	return state
}

func (m *moeSimulator) route(counts []float64, placement [][]int) *moeRoutingState {
	switch m.router {
	case common.MoERouterConcentrate:
		return m.routeConcentrate(counts, placement)
	case common.MoERouterHeuristic:
		return m.routeHeuristic(counts, placement)
	default:
		return m.routeSplit(counts, placement)
	}
}

func (m *moeSimulator) communicationCost(state *moeRoutingState) float64 {
	if m.numGPUs <= 1 {
		return 0
	}
	maxAssignments := 0.0
	for _, load := range state.loads {
		maxAssignments = math.Max(maxAssignments, load)
	}
	if maxAssignments == 0 {
		return 0
	}
	remoteFraction := 1 - 1/float64(m.numGPUs)
	bytesPerPhase := maxAssignments * remoteFraction * m.networkBytes
	phaseSeconds := bytesPerPhase/m.interconnectBW + m.interconnectLatency.Seconds()
	return 2 * phaseSeconds
}

func (m *moeSimulator) shouldRecordEPLBLoad() bool {
	stepsRemaining := vllmEPLBStepInterval - m.expertRearrangementStep
	return stepsRemaining <= vllmEPLBWindowSize
}

func (m *moeSimulator) recordEPLBLoad(counts []float64) {
	stride := m.numLayers * m.numExperts
	base := m.eplbLoadWindowStep * stride
	for layer := range m.numLayers {
		layerBase := base + layer*m.numExperts
		copy(m.eplbLoadWindow[layerBase:layerBase+m.numExperts], counts)
	}
	m.eplbLoadWindowStep++
	if m.eplbLoadWindowStep >= vllmEPLBWindowSize {
		m.eplbLoadWindowStep = 0
	}
}

func (m *moeSimulator) summedEPLBLogicalLoad() [][]float64 {
	loads := make([][]float64, m.numLayers)
	for layer := range m.numLayers {
		loads[layer] = make([]float64, m.numExperts)
	}
	stride := m.numLayers * m.numExperts
	for windowStep := range vllmEPLBWindowSize {
		windowBase := windowStep * stride
		for layer := range m.numLayers {
			layerBase := windowBase + layer*m.numExperts
			for expert := range m.numExperts {
				loads[layer][expert] += m.eplbLoadWindow[layerBase+expert]
			}
		}
	}
	return loads
}

// replacementCost models synchronous D'Hondt EPLB weight movement. The custom
// D'Hondt policy in the reference vLLM patch uses synchronous EPLB, so the
// transfer delay is added to the forward that triggers rearrangement. Transfers
// to different destination GPUs are treated as parallel within a layer; layers
// are accumulated serially. This is a simulator approximation of vLLM's real
// rearrange_expert_weights_inplace data movement.
func (m *moeSimulator) replacementCost(oldPlacements, newPlacements [][][]int) (time.Duration, int) {
	if m.numGPUs <= 1 {
		return 0, 0
	}
	totalSeconds := 0.0
	totalMoves := 0
	for layer := range m.numLayers {
		inboundMoves := make([]int, m.numGPUs)
		for expert, newRanks := range newPlacements[layer] {
			oldRanks := make(map[int]struct{}, len(oldPlacements[layer][expert]))
			for _, rank := range oldPlacements[layer][expert] {
				oldRanks[rank] = struct{}{}
			}
			for _, rank := range newRanks {
				if _, alreadyPresent := oldRanks[rank]; alreadyPresent {
					continue
				}
				inboundMoves[rank]++
				totalMoves++
			}
		}
		maxInbound := 0
		for _, moves := range inboundMoves {
			if moves > maxInbound {
				maxInbound = moves
			}
		}
		if maxInbound > 0 {
			totalSeconds += m.interconnectLatency.Seconds() +
				float64(maxInbound)*m.expertWeightBytes/m.interconnectBW
		}
	}
	return time.Duration(totalSeconds * float64(time.Second)), totalMoves
}

func (m *moeSimulator) rebalanceExperts() time.Duration {
	logicalLoads := m.summedEPLBLogicalLoad()
	newPlacements := make([][][]int, m.numLayers)
	for layer := range m.numLayers {
		newPlacements[layer], _ = dhondtPlaceOneLayer(
			logicalLoads[layer], m.physicalSlots, m.numGPUs,
		)
	}

	migrationLatency, moves := m.replacementCost(m.placements, newPlacements)
	m.placements = newPlacements
	m.lastReplacementMoves = moves
	m.placementGeneration++
	return migrationLatency
}

// advanceEPLBStep follows vLLM's EplbState.step ordering: optionally record
// this forward's load, increment the rearrangement counter, and rearrange once
// the configured interval is reached. The new mapping applies to the next
// simulated forward.
func (m *moeSimulator) advanceEPLBStep(counts []float64) time.Duration {
	if m.shouldRecordEPLBLoad() {
		m.recordEPLBLoad(counts)
	}

	m.expertRearrangementStep++
	if m.expertRearrangementStep < vllmEPLBStepInterval {
		return 0
	}
	m.expertRearrangementStep = 0
	return m.rebalanceExperts()
}

func (m *moeSimulator) latencyForTokens(tokens int) time.Duration {
	if tokens <= 0 {
		return 0
	}

	// EPLB state is global to an expert-parallel model. Serialize its simulated
	// forward-step accounting so concurrent HTTP requests observe one coherent
	// vLLM-style load window and rearrangement sequence.
	m.stateMu.Lock()
	defer m.stateMu.Unlock()

	counts := make([]float64, m.numExperts)
	for expert, probability := range m.probabilities {
		counts[expert] = float64(tokens*m.topK) * probability
	}

	cacheKey := moeLatencyCacheKey{generation: m.placementGeneration, tokens: tokens}
	latency, found := m.latencyCache[cacheKey]
	if !found {
		totalSeconds := 0.0
		for layer := range m.numLayers {
			state := m.route(counts, m.placements[layer])
			totalSeconds += m.maxGPUCost(state) + m.communicationCost(state)
		}
		latency = time.Duration(totalSeconds * float64(time.Second))
		m.latencyCache[cacheKey] = latency
	}

	// The load trace used for EPLB is the same logical expert demand that drove
	// this simulated forward. This mirrors vLLM's runtime source: per-forward
	// expert token counters accumulated into its sliding load window. The
	// current simulator generates those assignments from the configured
	// synthetic expert-popularity distribution rather than a real gate network.
	migrationLatency := m.advanceEPLBStep(counts)
	return latency + migrationLatency
}

func (s *SimContext) moePrefillLatency(params *TTFTParams) time.Duration {
	if s.moe == nil || params.DoRemotePrefill {
		return 0
	}
	tokens := params.PromptTokens - params.CachedPromptTokens
	if tokens < 0 {
		tokens = 0
	}
	return s.moe.latencyForTokens(tokens)
}

func (s *SimContext) moeDecodeLatency(params *InterTokenParams) time.Duration {
	if s.moe == nil {
		return 0
	}
	tokens := int(params.RunningReqs)
	if tokens < 1 {
		tokens = 1
	}
	return s.moe.latencyForTokens(tokens)
}
